#include "gemm_w4a4.h"

// Host launcher for the Ascend gemm_w4a4 pod.
//
// Phase 2c: packs the user's `GemmW4A4Params` into a typed-pointer
// `DeviceParams` struct that the device kernel can dereference
// without running into ccec's aicore-side `void* → T*` cast ban.
// The two structs are byte-compatible by construction (3 × 8 B
// pointers in act/wgt/out order); only this file knows the host side
// of that contract — `kernel_device.cpp` mirrors the layout with
// `__gm__ T*` fields. Keep them in sync.
//
// The Phase 2c mock dequant scale (0.5) is hardcoded device-side via
// TEXPANDS, not passed in over GM. PTO's TLOAD can't pull a ColMajor
// reduce tile out of an ND GlobalTensor (only ND2ND/DN2DN/NZ2NZ are
// supported), and FA's reference doesn't load reduce tiles from GM
// either; they come from in-tile reduce ops. Phase 3 derives the real
// per-row scale in-tile from ascales × wscales, so a dedicated GM
// buffer would never have paid off.
//
// `out` must be over-allocated by the smoke driver to hold both the
// cube ring (Phase 2b: kRingSlots × M × N fp32) AND a final vec_out
// segment (Phase 2c: 1 × M × N fp32) right after it. The launcher
// just forwards the base pointer.
//
// Synchronization: the kernel reads dev_params on entry, so we must
// wait for the stream to drain before freeing dev_params. The sync
// also lets the smoke driver compare the output to a reference
// without a separate sync step.
//
// `aclrtlaunch_svdquant_gemm_w4a4_kernel` is auto-generated by
// ascendc.cmake's host_stub.cpp; its include path is exposed via
// INTERFACE include propagation from the device static lib.

#include <acl/acl.h>
#include "aclrtlaunch_svdquant_gemm_w4a4_kernel.h"

namespace svdquant::ascend {

namespace {
struct DeviceParams {
    void* act;   // [Tile_M, Tile_K] half row-major (device addr)
    void* wgt;   // [Tile_N, Tile_K] half row-major (device addr)
    void* out;   // [(kRingSlots+1), Tile_M, Tile_N] fp32 (device addr) —
                 // first kRingSlots slots = cube ring (Phase 2b),
                 // final slot               = vec_out (Phase 2c).
};
}  // namespace

void gemm_w4a4(const GemmW4A4Params& p, void* stream) {
    auto raw_stream = static_cast<aclrtStream>(stream);

    DeviceParams dp{};
    dp.act = p.act.data;
    dp.wgt = p.wgt.data;
    dp.out = p.out.data;

    void* dev_params = nullptr;
    if (aclrtMalloc(&dev_params, sizeof(DeviceParams),
                    ACL_MEM_MALLOC_HUGE_FIRST) != ACL_SUCCESS) {
        return;
    }
    if (aclrtMemcpy(dev_params, sizeof(DeviceParams),
                    &dp, sizeof(DeviceParams),
                    ACL_MEMCPY_HOST_TO_DEVICE) != ACL_SUCCESS) {
        aclrtFree(dev_params);
        return;
    }

    // Single-CTA launch for Phase 2c. Grid sizing comes in Phase 3
    // when each cube core works on its own M/N chunk; here one cube +
    // 2 vec subblocks (mix 1:2) produce one tile and the smoke
    // validates both the cube ring slot and the vec_out segment.
    constexpr uint32_t blockDim = 1;
    aclrtlaunch_svdquant_gemm_w4a4_kernel(blockDim, raw_stream, dev_params);

    aclrtSynchronizeStream(raw_stream);
    aclrtFree(dev_params);
}

}  // namespace svdquant::ascend
