// Host launcher for the Ascend gemm_w4a4 pod.
//
// Phase 2f: signature is `(void* act, void* wgt, void* out, void* stream)` —
// raw NPU device pointers + opaque stream. The torch op extension at
// `csrc/python/host/svdquant_w4a4_op.cpp` calls this directly via
// `INVOKE_PTO_KERNEL`, with `arg.storage().data()` for the pointers
// and `c10_npu::getCurrentNPUStream()` for the stream. No struct
// wrapper, no dim args yet (Phase 2d kernel uses constexpr 64×128×128
// tile sizes; Phase 3 parameterizes them along with ascales/wscales/
// lora_*/bias).
//
// The host launcher still has to repack the user's pointers into a
// device-side `DeviceParams` struct (3 × 8 B typed pointers) because
// Phase 2d's kernel_device.cpp signature accepts a single
// `GM_ADDR params_addr` and dereferences typed members. That repack
// stays internal to this file — the public surface is just the 4
// argument host function.
//
// Synchronization is the caller's responsibility. The torch op
// wrapper either lets `c10_npu::OpCommand::RunOpApi` track the
// kernel for the npu graph executor (async, default) or wraps the
// call in `aclrtSynchronizeStream` for tests. We do NOT
// synchronize here so a mid-graph op doesn't introduce stalls.
//
// `aclrtlaunch_svdquant_gemm_w4a4_kernel` is auto-generated by
// ascendc.cmake's host_stub.cpp; its include path is exposed via
// INTERFACE include propagation from the device static lib.

#include "gemm_w4a4.h"

#include <acl/acl.h>
#include "aclrtlaunch_svdquant_gemm_w4a4_kernel.h"

namespace svdquant::ascend {

namespace {

// Mirrors the device-side `DeviceParams` in kernel_device.cpp by byte
// layout: 3 × 8 B device pointers in act/wgt/out order. Host can't
// share a header with the device file because that file is `[aicore]`
// and ccec's strict pointer-cast rules don't let it dereference a
// generic `void* __gm__` as a typed `__gm__ T*`. The two structs are
// kept in sync by hand; expansions in Phase 3 (ascales, wscales,
// lora_*) must be added in both files in the same order.
struct DeviceParams {
    void* act;   // [Tile_M, Tile_K] half row-major
    void* wgt;   // [Tile_N, Tile_K] half row-major
    void* out;   // [(kRingSlots + kNumTiles), Tile_M, Tile_N] fp32
};

}  // namespace

void gemm_w4a4(void* act, void* wgt, void* out, void* stream) {
    auto raw_stream = static_cast<aclrtStream>(stream);

    DeviceParams dp{act, wgt, out};

    void* dev_params = nullptr;
    if (aclrtMalloc(&dev_params, sizeof(DeviceParams),
                    ACL_MEM_MALLOC_HUGE_FIRST) != ACL_SUCCESS) {
        return;
    }
    if (aclrtMemcpy(dev_params, sizeof(DeviceParams),
                    &dp, sizeof(DeviceParams),
                    ACL_MEMCPY_HOST_TO_DEVICE) != ACL_SUCCESS) {
        aclrtFree(dev_params);
        return;
    }

    // Single-CTA launch for Phase 2f (mirrors Phase 2d). One cube +
    // 2 vec subblocks (mix 1:2) iterate kNumTiles=8 tiles into the
    // vec_out region. Phase 3 grid sizing comes when each cube core
    // works on its own M/N chunk.
    constexpr uint32_t blockDim = 1;
    aclrtlaunch_svdquant_gemm_w4a4_kernel(blockDim, raw_stream, dev_params);

    // Free the staging dev_params *after* draining the stream — the
    // kernel reads dev_params on entry, so freeing before the launch
    // completes would be use-after-free. Caller's responsibility to
    // manage stream-side fences if they want async semantics; for
    // now we synchronize here to keep the API simple. Phase 3 may
    // revisit this once the op is integrated into a torch_npu graph
    // executor that owns its own stream lifetime.
    aclrtSynchronizeStream(raw_stream);
    aclrtFree(dev_params);
}

}  // namespace svdquant::ascend
