#include "gemm_w4a4.h"

// Host launcher for the Ascend gemm_w4a4 pod.
//
// Phase 2b: packs the user's `GemmW4A4Params` (which holds `void*`
// device pointers wrapped in TensorRef) into a typed-pointer
// `DeviceParams` struct that the device kernel can dereference
// without running into ccec's aicore-side `void* → T*` cast ban.
// The two structs are byte-compatible by construction (3 × 8 B
// pointers, in act/wgt/out order), and only this file knows the
// host side of that contract — `kernel_device.cpp` mirrors the
// layout with `__gm__ T*` fields. Keep them in sync.
//
// Synchronization: the kernel now actually reads the params struct
// (Phase 1b's no-op didn't, so we could free dev_params eagerly).
// We must sync the stream before freeing or the kernel will read
// freed memory. The sync also lets the smoke driver compare the
// output to a reference without a separate sync step.
//
// `aclrtlaunch_svdquant_gemm_w4a4_kernel` is auto-generated by
// ascendc.cmake's host_stub.cpp; its include path is exposed via
// INTERFACE include propagation from the device static lib.

#include <acl/acl.h>
#include "aclrtlaunch_svdquant_gemm_w4a4_kernel.h"

namespace svdquant::ascend {

namespace {
struct DeviceParams {
    void* act;   // [Tile_M, Tile_K] half row-major (device addr)
    void* wgt;   // [Tile_N, Tile_K] half row-major (device addr)
    void* out;   // [kRingSlots, Tile_M, Tile_N] fp32 ring (device addr)
};
}  // namespace

void gemm_w4a4(const GemmW4A4Params& p, void* stream) {
    DeviceParams dp{};
    dp.act = p.act.data;
    dp.wgt = p.wgt.data;
    dp.out = p.out.data;

    void* dev_params = nullptr;
    if (aclrtMalloc(&dev_params, sizeof(DeviceParams),
                    ACL_MEM_MALLOC_HUGE_FIRST) != ACL_SUCCESS) {
        return;
    }
    if (aclrtMemcpy(dev_params, sizeof(DeviceParams),
                    &dp, sizeof(DeviceParams),
                    ACL_MEMCPY_HOST_TO_DEVICE) != ACL_SUCCESS) {
        aclrtFree(dev_params);
        return;
    }

    // Single-CTA launch for Phase 2b. Grid sizing comes in Phase 3
    // when each cube core works on its own M/N chunk; here one cube
    // produces one tile and the smoke validates that single tile.
    constexpr uint32_t blockDim = 1;
    aclrtlaunch_svdquant_gemm_w4a4_kernel(
        blockDim, static_cast<aclrtStream>(stream), dev_params);

    // The kernel reads dev_params on entry, so we must wait for the
    // stream to drain before freeing. Phase 1b's placeholder didn't
    // dereference, hence the previous eager free; that race window
    // is not safe anymore.
    aclrtSynchronizeStream(static_cast<aclrtStream>(stream));
    aclrtFree(dev_params);
}

}  // namespace svdquant::ascend
